name: Artists who are in a Country's top ten who also have Tracks in the same Country's top ten Benchmark

on:
  push:
    branches:
      - all-benchmarks
      - zip/q2

jobs:
    benchmark:
        name: Benchmark
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v1
            -   name: Use Node.js 10
                uses: actions/setup-node@v1
                with:
                    node-version: 10

            -   name: Install
                run: npm clean-install

            -   name: Build
                run: npm run build

            -   name: Run Benchmark
                run: node --no-warnings ./build/lib/index.js -n ArtistsInTopTenWithTopTenTracksByCountryBenchmark -i 10 -t 10 -o zip-artists-top10.log

            -   name: Upload results
                uses: actions/upload-artifact@v2
                with:
                  name: zip-artists-top10
                  path: zip-artists-top10.log
