name: Zip Primes with Values

on:
  push:
    branches:
      - all-benchmarks
      - zip/q3

jobs:
    benchmark:
        name: Benchmark
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v1
            -   name: Use Node.js 10
                uses: actions/setup-node@v1
                with:
                    node-version: 10

            -   name: Install
                run: npm clean-install

            -   name: Build
                run: npm run build

            -   name: Run Benchmark [COLLECTION_SIZE = 1K]
                run: node --no-warnings --max-old-space-size=2048 ./build/lib/index.js -n ZipPrimesBenchmark -s 1000 -i 30 -t 30 -o zip-primes-1K.log

            -   name: Run Benchmark [COLLECTION_SIZE = 100K]
                run: node --no-warnings --max-old-space-size=2048 ./build/lib/index.js -n ZipPrimesBenchmark -s 100000 -i 30 -t 30 -o zip-primes-100K.log

            -   name: Upload results
                uses: actions/upload-artifact@v2
                with:
                    name: zip-primes
                    path: ./*.log
